spring:
  datasource:
    dynamic:
      primary: first
      datasource:
#        用户数据库
        first:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/sgdb?characterEncoding=utf-8&serverTimezone=UTC
          username: root
          password: root
#        权限数据库
        second:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/sg_security?characterEncoding=utf-8&serverTimezone=UTC
          username: root
          password: root
  redis:
    host: 192.168.111.139
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1000ms
        min-idle: 0
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
server:
  port: 8888